## magic_item_database.gd
## Base de datos de objetos mágicos (D&D 2024).
## 124 objetos registrados.

extends Node

var _items: Dictionary = {}

func _ready() -> void:
	_register_all()

func get(item_id: String) -> MagicItemData: return _items.get(item_id)
func get_all() -> Array[MagicItemData]: return _items.values()
func get_by_rarity(r: ItemData.Rarity) -> Array[MagicItemData]:
	return _items.values().filter(func(x: MagicItemData) -> bool: return x.rarity == r)

func _register_all() -> void:
	_m("armadura_1", "Armadura +1", ItemData.Rarity.RARO, ItemData.ItemType.ARMOR, MagicItemData.Attunement.NONE, "+1 a la Clase de Armadura")
	_m("armadura_2", "Armadura +2", ItemData.Rarity.MUY_RARO, ItemData.ItemType.ARMOR, MagicItemData.Attunement.NONE, "+2 a la Clase de Armadura")
	_m("armadura_3", "Armadura +3", ItemData.Rarity.LEGENDARIO, ItemData.ItemType.ARMOR, MagicItemData.Attunement.NONE, "+3 a la Clase de Armadura")
	_m("arma_1", "Arma +1", ItemData.Rarity.INFRECUENTE, ItemData.ItemType.WEAPON, MagicItemData.Attunement.NONE, "+1 a tiradas de ataque y daño")
	_m("arma_2", "Arma +2", ItemData.Rarity.RARO, ItemData.ItemType.WEAPON, MagicItemData.Attunement.NONE, "+2 a tiradas de ataque y daño")
	_m("arma_3", "Arma +3", ItemData.Rarity.MUY_RARO, ItemData.ItemType.WEAPON, MagicItemData.Attunement.NONE, "+3 a tiradas de ataque y daño")
	_m("escudo_1", "Escudo +1", ItemData.Rarity.INFRECUENTE, ItemData.ItemType.SHIELD, MagicItemData.Attunement.NONE, "+1 CA adicional al escudo")
	_m("escudo_2", "Escudo +2", ItemData.Rarity.RARO, ItemData.ItemType.SHIELD, MagicItemData.Attunement.NONE, "+2 CA adicional al escudo")
	_m("escudo_3", "Escudo +3", ItemData.Rarity.MUY_RARO, ItemData.ItemType.SHIELD, MagicItemData.Attunement.NONE, "+3 CA adicional al escudo")
	_m("armadura_adamantina", "Armadura Adamantina", ItemData.Rarity.INFRECUENTE, ItemData.ItemType.ARMOR, MagicItemData.Attunement.NONE, "Los golpes críticos contra ti se vuelven normales")
	_m("armadura_de_resistencia", "Armadura de Resistencia", ItemData.Rarity.RARO, ItemData.ItemType.ARMOR, MagicItemData.Attunement.ANY, "Resistencia a un tipo de daño elegido")
	_m("armadura_elfica", "Armadura Élfica", ItemData.Rarity.RARO, ItemData.ItemType.ARMOR, MagicItemData.Attunement.NONE, "+1 CA, entrenamiento automático")
	_m("armadura_de_mithral", "Armadura de Mithral", ItemData.Rarity.INFRECUENTE, ItemData.ItemType.ARMOR, MagicItemData.Attunement.NONE, "Sin desventaja en Sigilo, sin requisito de FUE")
	_m("armadura_de_placas_de_la_etereidad", "Armadura de Placas de la Etereidad", ItemData.Rarity.LEGENDARIO, ItemData.ItemType.ARMOR, MagicItemData.Attunement.ANY, "Lanzas Forma Etérea 1/amanecer")
	_m("armadura_de_invulnerabilidad", "Armadura de Invulnerabilidad", ItemData.Rarity.LEGENDARIO, ItemData.ItemType.ARMOR, MagicItemData.Attunement.ANY, "Resistencia B/P/C; inmunidad 10min/amanecer")
	_m("malla_reluciente", "Malla Reluciente", ItemData.Rarity.COMUN, ItemData.ItemType.ARMOR, MagicItemData.Attunement.NONE, "La armadura nunca se ensucia")
	_m("armadura_abandonada", "Armadura Abandonada", ItemData.Rarity.COMUN, ItemData.ItemType.ARMOR, MagicItemData.Attunement.NONE, "Puedes quitarte la armadura como acción mágica")
	_m("armadura_humeante", "Armadura Humeante", ItemData.Rarity.COMUN, ItemData.ItemType.ARMOR, MagicItemData.Attunement.NONE, "Volutas de humo inofensivas mientras la llevas")
	_m("armadura_del_berserker", "Armadura del Berserker", ItemData.Rarity.RARO, ItemData.ItemType.ARMOR, MagicItemData.Attunement.ANY, "+1 ataque; maldita: furia en combate")
	_m("armadura_demoniaca", "Armadura Demoníaca", ItemData.Rarity.MUY_RARO, ItemData.ItemType.ARMOR, MagicItemData.Attunement.ANY, "+1 CA, idioma abisal, golpes sin armas 1d8")
	_m("cota_de_malla_elfica_encadenada", "Cota de Malla Élfica Encadenada", ItemData.Rarity.RARO, ItemData.ItemType.ARMOR, MagicItemData.Attunement.NONE, "+1 CA; competencia automática")
	_m("placa_enana", "Placa Enana", ItemData.Rarity.MUY_RARO, ItemData.ItemType.ARMOR, MagicItemData.Attunement.NONE, "+2 CA, reduce desplazamiento forzado 3m")
	_m("escamas_de_dragon", "Escamas de Dragón", ItemData.Rarity.MUY_RARO, ItemData.ItemType.ARMOR, MagicItemData.Attunement.ANY, "+1 CA, resistencia al tipo del dragón")
	_m("cuero_glamuroso_tachonado", "Cuero Glamuroso Tachonado", ItemData.Rarity.RARO, ItemData.ItemType.ARMOR, MagicItemData.Attunement.NONE, "+1 CA, aspecto ilusorio cambiable")
	_m("armadura_del_marinero", "Armadura del Marinero", ItemData.Rarity.INFRECUENTE, ItemData.ItemType.ARMOR, MagicItemData.Attunement.NONE, "Velocidad de natación, recuperas PG bajo el agua")
	_m("escudo_centinela", "Escudo Centinela", ItemData.Rarity.INFRECUENTE, ItemData.ItemType.SHIELD, MagicItemData.Attunement.NONE, "Ventaja en Iniciativa y Percepción")
	_m("escudo_de_atraccion_de_proyectiles", "Escudo de Atracción de Proyectiles", ItemData.Rarity.RARO, ItemData.ItemType.SHIELD, MagicItemData.Attunement.ANY, "Resistencia daño a distancia; maldito: atrae proyectiles")
	_m("escudo_de_la_caballeria", "Escudo de la Caballería", ItemData.Rarity.MUY_RARO, ItemData.ItemType.SHIELD, MagicItemData.Attunement.ANY, "+2 CA, golpe de escudo, campo protector")
	_m("escudo_de_proteccion_contra_proyectiles", "Escudo de Protección contra Proyectiles", ItemData.Rarity.RARO, ItemData.ItemType.SHIELD, MagicItemData.Attunement.ANY, "+2 CA vs ataques a distancia, redirigir ataques")
	_m("escudo_de_proteccion_contra_hechizos", "Escudo de Protección contra Hechizos", ItemData.Rarity.MUY_RARO, ItemData.ItemType.SHIELD, MagicItemData.Attunement.ANY, "Ventaja en saves vs conjuros, desventaja ataques de conjuro")
	_m("espada_sol", "Espada Sol", ItemData.Rarity.RARO, ItemData.ItemType.WEAPON, MagicItemData.Attunement.ANY, "+2 espada larga, 1d8 extra vs muertos vivientes, luz solar")
	_m("espada_lengua_de_fuego", "Espada Lengua de Fuego", ItemData.Rarity.RARO, ItemData.ItemType.WEAPON, MagicItemData.Attunement.ANY, "+2d6 daño de fuego mientras arde")
	_m("marca_de_nieve", "Marca de Nieve", ItemData.Rarity.MUY_RARO, ItemData.ItemType.WEAPON, MagicItemData.Attunement.ANY, "+1d6 frío, resistencia al fuego")
	_m("daga_de_veneno", "Daga de Veneno", ItemData.Rarity.RARO, ItemData.ItemType.WEAPON, MagicItemData.Attunement.NONE, "+1 ataque, veneno 2d10/amanecer")
	_m("hacha_lanzadora_enana", "Hacha Lanzadora Enana", ItemData.Rarity.MUY_RARO, ItemData.ItemType.WEAPON, MagicItemData.Attunement.ANY, "+3 ataque, 1d8 o 2d8 daño de fuerza al lanzar")
	_m("espada_bailarina", "Espada Bailarina", ItemData.Rarity.MUY_RARO, ItemData.ItemType.WEAPON, MagicItemData.Attunement.ANY, "Flota y ataca hasta 4 veces antes de regresar")
	_m("matadragones", "Matadragones", ItemData.Rarity.RARO, ItemData.ItemType.WEAPON, MagicItemData.Attunement.NONE, "+1 ataque, 3d6 extra vs dragones")
	_m("matagigantos", "Matagigantos", ItemData.Rarity.RARO, ItemData.ItemType.WEAPON, MagicItemData.Attunement.NONE, "+1 ataque, 2d6 vs gigantes, derribar DC 15")
	_m("espada_vorpal", "Espada Vorpal", ItemData.Rarity.LEGENDARIO, ItemData.ItemType.WEAPON, MagicItemData.Attunement.ANY, "+3, ignora resistencia cortante, decapitación")
	_m("espada_de_respuesta", "Espada de Respuesta", ItemData.Rarity.LEGENDARIO, ItemData.ItemType.WEAPON, MagicItemData.Attunement.ANY, "+3, reacción de ataque, ignora resistencia")
	_m("espada_de_vida_robada", "Espada de Vida Robada", ItemData.Rarity.RARO, ItemData.ItemType.WEAPON, MagicItemData.Attunement.ANY, "15 daño necrótico en 20 natural contra criaturas")
	_m("espada_viciosa", "Espada Viciosa", ItemData.Rarity.RARO, ItemData.ItemType.WEAPON, MagicItemData.Attunement.NONE, "+2d6 daño del mismo tipo en critico")
	_m("espada_afilada", "Espada Afilada", ItemData.Rarity.MUY_RARO, ItemData.ItemType.WEAPON, MagicItemData.Attunement.ANY, "Daño máximo a objetos, 14 cortante + agotamiento")
	_m("espada_de_las_heridas", "Espada de las Heridas", ItemData.Rarity.RARO, ItemData.ItemType.WEAPON, MagicItemData.Attunement.ANY, "2d6 necrótico, impide curación 1 hora")
	_m("oathbow", "Oathbow", ItemData.Rarity.MUY_RARO, ItemData.ItemType.WEAPON, MagicItemData.Attunement.ANY, "+3d6 vs enemigo jurado, desventaja otras armas")
	_m("espada_de_velocidad_cimitarra", "Espada de Velocidad (Cimitarra)", ItemData.Rarity.MUY_RARO, ItemData.ItemType.WEAPON, MagicItemData.Attunement.ANY, "+2 ataque, 1 ataque de bonus por turno")
	_m("maza_de_destruccion", "Maza de Destrucción", ItemData.Rarity.RARO, ItemData.ItemType.WEAPON, MagicItemData.Attunement.ANY, "+2d6 radiante vs infernales/muertos vivientes")
	_m("maza_del_terror", "Maza del Terror", ItemData.Rarity.RARO, ItemData.ItemType.WEAPON, MagicItemData.Attunement.ANY, "Miedo 9m DC 15, 3 cargas")
	_m("martillo_de_los_truenos", "Martillo de los Truenos", ItemData.Rarity.LEGENDARIO, ItemData.ItemType.WEAPON, MagicItemData.Attunement.ANY, "+1 ataque, 5d4 daño de fuerza con trueno")
	_m("tridente_de_mando_de_peces", "Tridente de Mando de Peces", ItemData.Rarity.INFRECUENTE, ItemData.ItemType.WEAPON, MagicItemData.Attunement.ANY, "Dominar bestia acuática DC 15")
	_m("bolsa_de_contencion", "Bolsa de Contención", ItemData.Rarity.INFRECUENTE, ItemData.ItemType.MAGIC, MagicItemData.Attunement.NONE, "Contiene 500 lbs en 64 pies cúbicos")
	_m("capa_de_invisibilidad", "Capa de Invisibilidad", ItemData.Rarity.LEGENDARIO, ItemData.ItemType.MAGIC, MagicItemData.Attunement.ANY, "Invisibilidad indefinida; 1 hora de cargas")
	_m("botas_de_la_velocidad", "Botas de la Velocidad", ItemData.Rarity.RARO, ItemData.ItemType.MAGIC, MagicItemData.Attunement.ANY, "Velocidad doble 10 min/día; desventaja ataques vs ti")
	_m("botas_de_levitacion", "Botas de Levitación", ItemData.Rarity.RARO, ItemData.ItemType.MAGIC, MagicItemData.Attunement.ANY, "Lanzas Levitar sobre ti mismo")
	_m("botas_de_elfo", "Botas de Elfo", ItemData.Rarity.INFRECUENTE, ItemData.ItemType.MAGIC, MagicItemData.Attunement.NONE, "Pasos sin ruido, ventaja en Sigilo")
	_m("botas_de_zancada_y_salto", "Botas de Zancada y Salto", ItemData.Rarity.INFRECUENTE, ItemData.ItemType.MAGIC, MagicItemData.Attunement.ANY, "Velocidad 9m, salto 9m usando 3m")
	_m("botas_de_arana", "Botas de Araña", ItemData.Rarity.INFRECUENTE, ItemData.ItemType.MAGIC, MagicItemData.Attunement.ANY, "Velocidad de escalar = velocidad")
	_m("brazales_de_arqueria", "Brazales de Arquería", ItemData.Rarity.INFRECUENTE, ItemData.ItemType.MAGIC, MagicItemData.Attunement.ANY, "Competencia y +2 daño con arcos")
	_m("brazales_de_defensa", "Brazales de Defensa", ItemData.Rarity.RARO, ItemData.ItemType.MAGIC, MagicItemData.Attunement.ANY, "+2 CA sin armadura ni escudo")
	_m("capa_de_proteccion", "Capa de Protección", ItemData.Rarity.INFRECUENTE, ItemData.ItemType.MAGIC, MagicItemData.Attunement.ANY, "+1 CA y tiradas de salvación")
	_m("capa_de_desplazamiento", "Capa de Desplazamiento", ItemData.Rarity.RARO, ItemData.ItemType.MAGIC, MagicItemData.Attunement.ANY, "Desventaja en ataques vs ti; cesa al recibir daño")
	_m("capa_de_elfo", "Capa de Elfo", ItemData.Rarity.INFRECUENTE, ItemData.ItemType.MAGIC, MagicItemData.Attunement.ANY, "Desventaja en Percepción vs ti")
	_m("cinturon_de_fuerza_de_gigante_colina", "Cinturón de Fuerza de Gigante (colina)", ItemData.Rarity.RARO, ItemData.ItemType.MAGIC, MagicItemData.Attunement.ANY, "FUE pasa a 21")
	_m("cinturon_de_fuerza_de_gigante_escarcha", "Cinturón de Fuerza de Gigante (escarcha)", ItemData.Rarity.MUY_RARO, ItemData.ItemType.MAGIC, MagicItemData.Attunement.ANY, "FUE pasa a 23")
	_m("cinturon_de_fuerza_de_gigante_fuego", "Cinturón de Fuerza de Gigante (fuego)", ItemData.Rarity.MUY_RARO, ItemData.ItemType.MAGIC, MagicItemData.Attunement.ANY, "FUE pasa a 25")
	_m("cinturon_de_fuerza_de_gigante_nube", "Cinturón de Fuerza de Gigante (nube)", ItemData.Rarity.LEGENDARIO, ItemData.ItemType.MAGIC, MagicItemData.Attunement.ANY, "FUE pasa a 27")
	_m("cinturon_de_fuerza_de_gigante_tormenta", "Cinturón de Fuerza de Gigante (tormenta)", ItemData.Rarity.LEGENDARIO, ItemData.ItemType.MAGIC, MagicItemData.Attunement.ANY, "FUE pasa a 29")
	_m("guanteletes_de_poder_del_ogro", "Guanteletes de Poder del Ogro", ItemData.Rarity.INFRECUENTE, ItemData.ItemType.MAGIC, MagicItemData.Attunement.ANY, "FUE pasa a 19")
	_m("diadema_de_intelecto", "Diadema de Intelecto", ItemData.Rarity.INFRECUENTE, ItemData.ItemType.MAGIC, MagicItemData.Attunement.ANY, "INT pasa a 19")
	_m("amuleto_de_salud", "Amuleto de Salud", ItemData.Rarity.RARO, ItemData.ItemType.MAGIC, MagicItemData.Attunement.ANY, "CON pasa a 19")
	_m("anillo_de_proteccion", "Anillo de Protección", ItemData.Rarity.RARO, ItemData.ItemType.MISC, MagicItemData.Attunement.ANY, "+1 CA y salvaciones")
	_m("anillo_de_invisibilidad", "Anillo de Invisibilidad", ItemData.Rarity.LEGENDARIO, ItemData.ItemType.MISC, MagicItemData.Attunement.ANY, "Invisibilidad indefinida")
	_m("anillo_de_tres_deseos", "Anillo de Tres Deseos", ItemData.Rarity.LEGENDARIO, ItemData.ItemType.MISC, MagicItemData.Attunement.NONE, "Lanza Deseo 3 veces, luego no mágico")
	_m("anillo_de_regeneracion", "Anillo de Regeneración", ItemData.Rarity.MUY_RARO, ItemData.ItemType.MISC, MagicItemData.Attunement.ANY, "Recuperas 1d6 PG cada 10 minutos")
	_m("anillo_de_resistencia_a_los_conjuros", "Anillo de Resistencia a los Conjuros", ItemData.Rarity.RARO, ItemData.ItemType.MISC, MagicItemData.Attunement.NONE, "Resistencia a un tipo de daño (según gema)")
	_m("anillo_de_almacenamiento_de_conjuros", "Anillo de Almacenamiento de Conjuros", ItemData.Rarity.RARO, ItemData.ItemType.MISC, MagicItemData.Attunement.ANY, "Almacena hasta nivel 5 de conjuros")
	_m("anillo_de_accion_libre", "Anillo de Acción Libre", ItemData.Rarity.RARO, ItemData.ItemType.MISC, MagicItemData.Attunement.ANY, "Sin terreno difícil, sin reducción de velocidad")
	_m("anillo_de_telekinesia", "Anillo de Telekinesia", ItemData.Rarity.MUY_RARO, ItemData.ItemType.MISC, MagicItemData.Attunement.ANY, "Lanzas Telequinesia")
	_m("anillo_de_caida_de_pluma", "Anillo de Caída de Pluma", ItemData.Rarity.RARO, ItemData.ItemType.MISC, MagicItemData.Attunement.ANY, "Caes a 18m/ronda sin daño")
	_m("anillo_de_natacion", "Anillo de Natación", ItemData.Rarity.INFRECUENTE, ItemData.ItemType.MISC, MagicItemData.Attunement.NONE, "Velocidad de natación 12m")
	_m("anillo_de_salto", "Anillo de Salto", ItemData.Rarity.INFRECUENTE, ItemData.ItemType.MISC, MagicItemData.Attunement.ANY, "Lanzas Salto sobre ti mismo")
	_m("anillo_de_mente_blindada", "Anillo de Mente Blindada", ItemData.Rarity.INFRECUENTE, ItemData.ItemType.MISC, MagicItemData.Attunement.ANY, "Inmunidad lectura de mente; guardar alma")
	_m("anillo_de_vision_x", "Anillo de Visión X", ItemData.Rarity.RARO, ItemData.ItemType.MISC, MagicItemData.Attunement.ANY, "Visión X 9m 1 minuto; riesgo de agotamiento")
	_m("baculo_del_mago", "Báculo del Mago", ItemData.Rarity.LEGENDARIO, ItemData.ItemType.MISC, MagicItemData.Attunement.ANY, "+2 ataques conjuro, 50 cargas, conjuros variados")
	_m("baculo_de_poder", "Báculo de Poder", ItemData.Rarity.MUY_RARO, ItemData.ItemType.MISC, MagicItemData.Attunement.ANY, "+2 CA/saves/ataques, conjuros, 20 cargas")
	_m("baculo_de_golpeo", "Báculo de Golpeo", ItemData.Rarity.MUY_RARO, ItemData.ItemType.MISC, MagicItemData.Attunement.ANY, "+3 bastón, 1d6 fuerza por carga, 10 cargas")
	_m("baculo_de_curacion", "Báculo de Curación", ItemData.Rarity.RARO, ItemData.ItemType.MISC, MagicItemData.Attunement.ANY, "Conjuros de curación, 10 cargas")
	_m("baculo_de_fuego", "Báculo de Fuego", ItemData.Rarity.MUY_RARO, ItemData.ItemType.MISC, MagicItemData.Attunement.ANY, "Resistencia fuego, conjuros de fuego, 10 cargas")
	_m("baculo_de_escarcha", "Báculo de Escarcha", ItemData.Rarity.MUY_RARO, ItemData.ItemType.MISC, MagicItemData.Attunement.ANY, "Resistencia frío, conjuros de frío, 10 cargas")
	_m("baculo_de_la_serpiente", "Báculo de la Serpiente", ItemData.Rarity.INFRECUENTE, ItemData.ItemType.MISC, MagicItemData.Attunement.ANY, "Cabeza de serpiente anima 1d6+3d6 daño")
	_m("varita_de_misiles_magicos", "Varita de Misiles Mágicos", ItemData.Rarity.INFRECUENTE, ItemData.ItemType.MISC, MagicItemData.Attunement.NONE, "Proyectil Mágico nv1-3, 7 cargas")
	_m("varita_de_bolas_de_fuego", "Varita de Bolas de Fuego", ItemData.Rarity.RARO, ItemData.ItemType.MISC, MagicItemData.Attunement.ANY, "Bola de Fuego nv3-5, 7 cargas")
	_m("varita_de_rayos", "Varita de Rayos", ItemData.Rarity.RARO, ItemData.ItemType.MISC, MagicItemData.Attunement.ANY, "Rayo nv3-5, 7 cargas")
	_m("varita_de_maravillas", "Varita de Maravillas", ItemData.Rarity.RARO, ItemData.ItemType.MISC, MagicItemData.Attunement.ANY, "Efecto mágico aleatorio 36m, 7 cargas")
	_m("varita_de_polimorfar", "Varita de Polimorfar", ItemData.Rarity.MUY_RARO, ItemData.ItemType.MISC, MagicItemData.Attunement.ANY, "Polimorfar DC 15, 7 cargas")
	_m("varita_de_miedo", "Varita de Miedo", ItemData.Rarity.RARO, ItemData.ItemType.MISC, MagicItemData.Attunement.ANY, "Conjuro Miedo cono 18m, 7 cargas")
	_m("varita_del_mago_de_guerra_1", "Varita del Mago de Guerra +1", ItemData.Rarity.INFRECUENTE, ItemData.ItemType.MISC, MagicItemData.Attunement.ANY, "+1 a ataques de conjuro")
	_m("varita_del_mago_de_guerra_2", "Varita del Mago de Guerra +2", ItemData.Rarity.RARO, ItemData.ItemType.MISC, MagicItemData.Attunement.ANY, "+2 a ataques de conjuro")
	_m("varita_del_mago_de_guerra_3", "Varita del Mago de Guerra +3", ItemData.Rarity.MUY_RARO, ItemData.ItemType.MISC, MagicItemData.Attunement.ANY, "+3 a ataques de conjuro")
	_m("cuentas_de_fuerza", "Cuentas de Fuerza", ItemData.Rarity.RARO, ItemData.ItemType.MAGIC, MagicItemData.Attunement.NONE, "Explosión 5d4 fuerza, esfera atrapadora")
	_m("esfera_de_aniquilacion", "Esfera de Aniquilación", ItemData.Rarity.LEGENDARIO, ItemData.ItemType.MAGIC, MagicItemData.Attunement.NONE, "Agujero 60cm destruye materia; 8d10 fuerza")
	_m("bolsa_de_trucos", "Bolsa de Trucos", ItemData.Rarity.INFRECUENTE, ItemData.ItemType.MAGIC, MagicItemData.Attunement.NONE, "Crea criaturas aleatorias de objetos mágicos")
	_m("espejo_de_trampa_vital", "Espejo de Trampa Vital", ItemData.Rarity.MUY_RARO, ItemData.ItemType.MAGIC, MagicItemData.Attunement.NONE, "Atrapa criaturas en celdas extradimensionales")
	_m("decantador_de_agua_interminable", "Decantador de Agua Interminable", ItemData.Rarity.INFRECUENTE, ItemData.ItemType.MAGIC, MagicItemData.Attunement.NONE, "Produce 1-30 galones de agua")
	_m("cubo_de_fuerza", "Cubo de Fuerza", ItemData.Rarity.RARO, ItemData.ItemType.MAGIC, MagicItemData.Attunement.ANY, "Conjuros de nv1-5, recupera 1d6 cargas/día")
	_m("agujero_portatil", "Agujero Portátil", ItemData.Rarity.RARO, ItemData.ItemType.MAGIC, MagicItemData.Attunement.NONE, "Hoyo extradimensional de 3m de profundidad")
	_m("cristal_de_bola", "Cristal de Bola", ItemData.Rarity.MUY_RARO, ItemData.ItemType.MAGIC, MagicItemData.Attunement.ANY, "Lanzas Escrutinio DC 17")
	_m("alfombra_voladora", "Alfombra Voladora", ItemData.Rarity.MUY_RARO, ItemData.ItemType.MAGIC, MagicItemData.Attunement.NONE, "Vuela a 9-24m según tamaño")
	_m("perla_de_poder", "Perla de Poder", ItemData.Rarity.INFRECUENTE, ItemData.ItemType.MAGIC, MagicItemData.Attunement.ANY, "Recuperas espacio nv3 o inferior/amanecer")
	_m("colmillo_de_pergamino_de_conjuro", "Colmillo de Pergamino de Conjuro", ItemData.Rarity.MUNDANO, ItemData.ItemType.CONSUMABLE, MagicItemData.Attunement.NONE, "Lanza el conjuro una vez, luego se deshace")
	_m("pocion_de_curacion", "Pocion de Curación", ItemData.Rarity.COMUN, ItemData.ItemType.CONSUMABLE, MagicItemData.Attunement.NONE, "Recuperas 2d4+2 PG")
	_m("pocion_de_curacion_mayor", "Pocion de Curación Mayor", ItemData.Rarity.INFRECUENTE, ItemData.ItemType.CONSUMABLE, MagicItemData.Attunement.NONE, "Recuperas 4d4+4 PG")
	_m("pocion_de_curacion_superior", "Pocion de Curación Superior", ItemData.Rarity.RARO, ItemData.ItemType.CONSUMABLE, MagicItemData.Attunement.NONE, "Recuperas 8d4+8 PG")
	_m("pocion_de_curacion_suprema", "Pocion de Curación Suprema", ItemData.Rarity.MUY_RARO, ItemData.ItemType.CONSUMABLE, MagicItemData.Attunement.NONE, "Recuperas 10d4+20 PG")
	_m("pocion_de_heroismo", "Pocion de Heroismo", ItemData.Rarity.RARO, ItemData.ItemType.CONSUMABLE, MagicItemData.Attunement.NONE, "10 PG temporales, efecto Bendición 1 hora")
	_m("pocion_de_velocidad", "Pocion de Velocidad", ItemData.Rarity.MUY_RARO, ItemData.ItemType.CONSUMABLE, MagicItemData.Attunement.NONE, "Celeridad 1 minuto, sin letargo posterior")
	_m("pocion_de_invisibilidad", "Pocion de Invisibilidad", ItemData.Rarity.RARO, ItemData.ItemType.CONSUMABLE, MagicItemData.Attunement.NONE, "Invisibilidad 1 hora; acaba al atacar")
	_m("pocion_de_gran_invisibilidad", "Pocion de Gran Invisibilidad", ItemData.Rarity.MUY_RARO, ItemData.ItemType.CONSUMABLE, MagicItemData.Attunement.NONE, "Invisibilidad 1 hora incluso atacando")
	_m("pocion_de_vuelo", "Pocion de Vuelo", ItemData.Rarity.MUY_RARO, ItemData.ItemType.CONSUMABLE, MagicItemData.Attunement.NONE, "Velocidad de vuelo = velocidad 1 hora")
	_m("pocion_de_vitalidad", "Pocion de Vitalidad", ItemData.Rarity.MUY_RARO, ItemData.ItemType.CONSUMABLE, MagicItemData.Attunement.NONE, "Elimina agotamiento, cura al máximo 24h")
	_m("pocion_de_resistencia", "Pocion de Resistencia", ItemData.Rarity.INFRECUENTE, ItemData.ItemType.CONSUMABLE, MagicItemData.Attunement.NONE, "Resistencia a un tipo de daño 1 hora")
	_m("elixir_de_salud", "Elixir de Salud", ItemData.Rarity.RARO, ItemData.ItemType.CONSUMABLE, MagicItemData.Attunement.NONE, "Cura enfermedades, elimina cegado/paralizado/envenenado")
	_m("aceite_de_nitidez", "Aceite de Nitidez", ItemData.Rarity.MUY_RARO, ItemData.ItemType.CONSUMABLE, MagicItemData.Attunement.NONE, "Cubre arma, se convierte en arma +3")
	_m("ungüento_de_keoghtom", "Ungüento de Keoghtom", ItemData.Rarity.INFRECUENTE, ItemData.ItemType.MAGIC, MagicItemData.Attunement.NONE, "Recupera 2d8+2 PG, elimina envenenado")

func _m(id: String, name: String, rarity: ItemData.Rarity, itype: ItemData.ItemType,
		att: MagicItemData.Attunement, effect: String) -> void:
	var m := MagicItemData.new()
	m.item_id = id; m.display_name = name; m.rarity = rarity
	m.item_type = itype; m.attunement = att; m.effect = effect
	m.is_magical = true
	_items[id] = m
